# Generated by Django 5.2.11 on 2026-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massive_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
